@startuml

hide empty members
'hide circle


'Enums
enum WebResourceType {
    Download
    Information
    Explore
    View
}

enum AccessControl {
    Open
    Embargoed
    Controlled
}

enum CompletionState {
    Complete
    InProgress
}

enum AgentType {
    Person
    Organization
}


'Entity-like
class Agent {
    * id: String!
    agent_id: String!
    agentType: AgentType
}

class Modality {
    * id: String!
    name: String!
    handle: String
}

class SpecimenType {
    * id: String!
    name: String!
    handle: String
}


class WebResource {
    * id: String!
    handle: String
    title: String!
    shortTitle: String!
    url: String!
    rrid: String
}

class Collection {
    * id: String!
    handle: String!
    title: String!
    shortTitle: String!
    description: String!
    lastUpdatedDate: Date
    doi: String
    rrid: String
    citation: String
}

class Program {
    * id: String!
    handle: String!
    title: String!
    shortTitle: String!
    description: String!
}

class Subprogram {
    * id: String!
    handle: String!
    title: String!
    shortTitle: String!
    description: String!
}

class Project {
    * id: String!
    handle: String
    title: String!
    shortTitle: String!
    description: String!
}

class Protocol {
    * id: String!
    handle: String
    title: String!
    shortTitle: String!
}

class Person {
    * id: String!
    name: String!
    givenName: String!
    familyName: String!
    handle: String
    orcid: String
}

class Organization {
    * id: String
    name: String!
    handle: String
    ror: String
}

class License {
    * id: String!
    handle: String
    name: String!
    title: String!
    shortTitle: String!
}

class Award {
    * id: String
    name: String!
    title: String!
    identifier: String!
    reportSymbol: String
}

class Technique {
    * id: String!
    handle: String
    name: String!
}

class Species {
    * id: String!
    name: String!
    common_name: String!
    scientific_name: String
    ncbi_taxonomy_id: String!
    rrid: String
}

class SpecimenCount {
    * id: String!
    count: Int
}

class Contact {
    * id: String!
    name: String!
    email: String
}

'Relationships
Agent --o| Person : person
Agent --o| Organization : organization

Agent --|| AgentType : type

SpecimenCount --|| SpecimenType : specimenType

WebResource --|| WebResourceType : type

Technique --|{ Protocol : protocol

Collection --|{  Modality : modality
Collection --|{  Species : species
Collection --|{ SpecimenCount : specimenCount
Collection --|{  Technique : technique
Collection --||  AccessControl : accessControl
Collection --||  CompletionState : completionState
Collection --|| License : license

Award --|| Agent : funder
Award --|| Agent : awardee

Contact --o| Agent: agent

Project --|{ Collection : collections
Project --|{  Award : fundingSource
Project --|{  WebResource : highlightedWebResources
Project --|{ Agent : creator
Project --o{  Agent : contributor
Project --o{  Contact : contact


circle webResource
Collection --o{ webResource
Protocol --|| webResource
Program --|| webResource
Subprogram --|| webResource
Project --o|  webResource
License --|| webResource
webResource --> WebResource

Project --|> Program
Program --|> Subprogram
Project --|{ Subprogram : subprogram
Subprogram --|| Program : program

@enduml